# SVD = Singular Value Decomposition

$$
  M = U \Sigma V^\dagger.
$$

In [1]:
import numpy as np

## SVD of a 2X2 matrix

In [2]:
# SVD of a 2X2 matrix
M = np.array([[1, 2],
              [3, 4]])
print('M=\n', M)

U,S,Vd = np.linalg.svd(M)
print('U=\n', U)
print('S=\n', S)
print('Vd=\n', Vd)

M=
 [[1 2]
 [3 4]]
U=
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S=
 [5.4649857  0.36596619]
Vd=
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [3]:
# check

# this gives the wrong answer because S is a vector
print('U S Vd=\n', U @ S @ Vd)
print('[S]=\n', np.diag(S))

# convert S to a diagonal matrix and check again
print('U [S] Vd=\n', U @ np.diag(S) @ Vd)

U S Vd=
 [-2.49789853  4.87447463]
[S]=
 [[5.4649857  0.        ]
 [0.         0.36596619]]
U [S] Vd=
 [[1. 2.]
 [3. 4.]]


In [4]:
np.diag(S)

array([[5.4649857 , 0.        ],
       [0.        , 0.36596619]])

In [5]:
Ud = np.transpose(U)
print('Ud U=\n', Ud @ U)
print('U Ud=\n', U @ Ud)

V = np.transpose(Vd)
print('Vd V=\n', Vd @ V)
print('V Vd=\n', V @ Vd)

Ud U=
 [[1.00000000e+00 9.98502693e-17]
 [9.98502693e-17 1.00000000e+00]]
U Ud=
 [[1.00000000e+00 3.00701513e-16]
 [3.00701513e-16 1.00000000e+00]]
Vd V=
 [[1.000000e+00 1.145223e-18]
 [1.145223e-18 1.000000e+00]]
V Vd=
 [[ 1.000000e+00 -1.145223e-18]
 [-1.145223e-18  1.000000e+00]]


## SVD of a 4X2 matrix

In [6]:
# SVD of a 4X2 matrix
M = np.array(range(8))
print('M=\n', M)
M = np.reshape(M, (4, 2))
print('M=\n',M)

U,S,Vd = np.linalg.svd(M)
print('U=\n', U)
print('S=\n', S)
print('Vd=\n', Vd)

M=
 [0 1 2 3 4 5 6 7]
M=
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
U=
 [[-0.0656451  -0.83408076 -0.38578674 -0.38880405]
 [-0.30394881 -0.45564802  0.22458489  0.80595386]
 [-0.54225252 -0.07721528  0.70819044 -0.44549557]
 [-0.78055624  0.30121746 -0.54698859  0.02834576]]
S=
 [11.80788803  0.75748278]
Vd=
 [[-0.63180182 -0.77512996]
 [ 0.77512996 -0.63180182]]


In [7]:
# check

# this fails because full matrices is set to be True
print('U [S] Vd=\n', U @ np.diag(S) @ Vd)

ValueError: shapes (4,4) and (2,2) not aligned: 4 (dim 1) != 2 (dim 0)

In [8]:
U,S,Vd = np.linalg.svd(M, full_matrices=False)
print('U=\n', U)
print('S=\n', S)
print('Vd=\n', Vd)

# check
print('U [S] Vd=\n', U @ np.diag(S) @ Vd)

U=
 [[-0.0656451  -0.83408076]
 [-0.30394881 -0.45564802]
 [-0.54225252 -0.07721528]
 [-0.78055624  0.30121746]]
S=
 [11.80788803  0.75748278]
Vd=
 [[-0.63180182 -0.77512996]
 [ 0.77512996 -0.63180182]]
U [S] Vd=
 [[-2.23890725e-18  1.00000000e+00]
 [ 2.00000000e+00  3.00000000e+00]
 [ 4.00000000e+00  5.00000000e+00]
 [ 6.00000000e+00  7.00000000e+00]]


## SVD of a 2X4 matrix

In [9]:
# SVD of a 4X2 matrix
M = np.array(range(8))
print('M=\n', M)
M = np.reshape(M, (2, 4))
print('M=\n',M)

U,S,Vd = np.linalg.svd(M)
print('U=\n', U)
print('S=\n', S)
print('Vd=\n', Vd)

M=
 [0 1 2 3 4 5 6 7]
M=
 [[0 1 2 3]
 [4 5 6 7]]
U=
 [[-0.29370412 -0.95589638]
 [-0.95589638  0.29370412]]
S=
 [11.73352876  1.52456641]
Vd=
 [[-0.32586834 -0.43236661 -0.53886488 -0.64536315]
 [ 0.77059057  0.33624265 -0.09810528 -0.5324532 ]
 [-0.38578674  0.22458489  0.70819044 -0.54698859]
 [-0.38880405  0.80595386 -0.44549557  0.02834576]]


In [10]:
# check

# this fails because full matrices is set to be True
print('U [S] Vd=\n', U @ np.diag(S) @ Vd)

ValueError: shapes (2,2) and (4,4) not aligned: 2 (dim 1) != 4 (dim 0)

In [11]:
U,S,Vd = np.linalg.svd(M, full_matrices=False)
print('U=\n', U)
print('S=\n', S)
print('Vd=\n', Vd)

# check
print('U [S] Vd=\n', U @ np.diag(S) @ Vd)

U=
 [[-0.29370412 -0.95589638]
 [-0.95589638  0.29370412]]
S=
 [11.73352876  1.52456641]
Vd=
 [[-0.32586834 -0.43236661 -0.53886488 -0.64536315]
 [ 0.77059057  0.33624265 -0.09810528 -0.5324532 ]]
U [S] Vd=
 [[-1.87949788e-15  1.00000000e+00  2.00000000e+00  3.00000000e+00]
 [ 4.00000000e+00  5.00000000e+00  6.00000000e+00  7.00000000e+00]]


In [12]:
## SVD truncation and approximation

In [13]:
D = 6
M = np.random.rand(D,D)
print('M=\n', M)

U,S,Vd = np.linalg.svd(M)
print('S=\n', S)

for D_cut in range(1,D+1):
    print('D_cut =', D_cut)
    S_cut = np.zeros_like(S)
    S_cut[:D_cut] = S[:D_cut]
    print('S_cut=\n', S_cut)    
    Diff = U @ np.diag(S_cut) @ Vd - M
    print('Max Diff =', np.max(Diff))
    print()


M=
 [[0.66268343 0.22596695 0.16618302 0.00585498 0.06941572 0.09741379]
 [0.35464831 0.09194054 0.20264719 0.26038838 0.12831224 0.33326903]
 [0.57091312 0.44453407 0.32430652 0.73867398 0.06032826 0.56859923]
 [0.07019451 0.18462956 0.8179159  0.69584693 0.18585568 0.38008879]
 [0.41617334 0.9044078  0.11109555 0.61755396 0.6926576  0.0632064 ]
 [0.36204126 0.96271213 0.59966001 0.96329888 0.95408193 0.05178084]]
S=
 [2.67511122 0.97401451 0.78723203 0.38954142 0.15145752 0.05477693]
D_cut = 1
S_cut=
 [2.67511122 0.         0.         0.         0.         0.        ]
Max Diff = 0.37179891742742316

D_cut = 2
S_cut=
 [2.67511122 0.97401451 0.         0.         0.         0.        ]
Max Diff = 0.32976964806484155

D_cut = 3
S_cut=
 [2.67511122 0.97401451 0.78723203 0.         0.         0.        ]
Max Diff = 0.1397694834712166

D_cut = 4
S_cut=
 [2.67511122 0.97401451 0.78723203 0.38954142 0.         0.        ]
Max Diff = 0.06613694211989854

D_cut = 5
S_cut=
 [2.67511122 0.974014

In [14]:
D = 4
M = np.array(range(D*D))
M = np.reshape(M, (D, D))
print('M=\n', M)

U,S,Vd = np.linalg.svd(M)
print('S=\n', S)

for D_cut in range(1,D+1):
    print('D_cut =', D_cut)
    S_cut = np.zeros_like(S)
    S_cut[:D_cut] = S[:D_cut]
    print('S_cut=\n', S_cut)    
    Diff = U @ np.diag(S_cut) @ Vd - M
    print('Max Diff =', np.max(Diff))
    print()



M=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
S=
 [3.51399637e+01 2.27661021e+00 1.79164689e-15 9.84875082e-17]
D_cut = 1
S_cut=
 [35.13996366  0.          0.          0.        ]
Max Diff = 1.3662601021279475

D_cut = 2
S_cut=
 [35.13996366  2.27661021  0.          0.        ]
Max Diff = 5.329070518200751e-15

D_cut = 3
S_cut=
 [3.51399637e+01 2.27661021e+00 1.79164689e-15 0.00000000e+00]
Max Diff = 5.329070518200751e-15

D_cut = 4
S_cut=
 [3.51399637e+01 2.27661021e+00 1.79164689e-15 9.84875082e-17]
Max Diff = 5.329070518200751e-15

