# Tensor network

## Import Tor10 and other modules

This notebook requires [Tor10](https://github.com/kaihsin/Tor10)

In [1]:
import tor10
import numpy as np 
import torch 
import copy

## Tor10 example.
**Based on the offitial `example.py'.**

## Bond

### Regular bonds

In [19]:
bd1 = tor10.Bond(2)
print(bd1)

bd2 = tor10.Bond(2, tor10.BD_REG)
print(bd2)

bd3 = tor10.Bond(2)
print(bd3)

print(bd1 == bd2) ## This should be true
print(bd1 is bd2) ## This should be false

print(bd1 == bd3) ## This should be true
print(bd1 is bd3) ## This should be false

Dim = 2 |
REG     :

Dim = 2 |
REG     :

Dim = 2 |
REG     :

True
False
True
False


In [20]:
bd1 = tor10.Bond(3)
print(bd1)

bd2 = tor10.Bond(4)
print(bd2)

print(bd1 == bd2) ## This should be false

Dim = 3 |
REG     :

Dim = 4 |
REG     :

False


### Bra bonds and Ket bonds

In [22]:
bra = tor10.Bond(2, tor10.BD_BRA)
print(bra)

ket = tor10.Bond(2, tor10.BD_KET)
print(ket)

print(bra == ket)

Dim = 2 |
BRA     :

Dim = 2 |
KET     :

False


### Combine bonds

In [26]:
## Combine:
a = tor10.Bond(3)
b = tor10.Bond(4)

print(a)
print(b)
a.combine(b)
print(a)

a = tor10.Bond(3)
b = tor10.Bond(4)

print(a)
print(b)
b.combine(a)
print(b)

Dim = 3 |
REG     :

Dim = 4 |
REG     :

Dim = 12 |
REG     :

Dim = 3 |
REG     :

Dim = 4 |
REG     :

Dim = 12 |
REG     :



## UniTensor

### Create a tensor

In [31]:
## UniTensor:
#=========================================================
# Create Tensor
a = tor10.UniTensor(bonds=[tor10.Bond(3),tor10.Bond(4)],rowrank=1,name="a")
print(a)

c = tor10.UniTensor(bonds=[tor10.Bond(3),tor10.Bond(4),tor10.Bond(5)],N_inbond=1,labels=[-3,4,1],name="b")
print(c)

e = tor10.UniTensor(bonds=[tor10.Bond(6),tor10.Bond(6)],N_inbond=1,is_diag=True, name="e")
print(e)
print(e.shape)

f = tor10.UniTensor(bonds=[tor10.Bond(3),tor10.Bond(4),tor10.Bond(5)],N_inbond=2,labels=[-3,4,1],dtype=torch.float32,name="f")
print(f)
print(f.shape)

Tensor name: a
is_diag    : False
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)



TypeError: __init__() got an unexpected keyword argument 'N_inbond'

### Label

In [32]:
# Labels related 
g = Tor10.UniTensor(bonds=[Tor10.Bond(3),Tor10.Bond(4)],N_inbond=1,labels=[5,6])
print(g.labels)
g.SetLabel(-1,1)
print(g.labels)

new_label=[-1,-2]
g.SetLabels(new_label)
print(g.labels)

[5 6]
[ 5 -1]
[-1 -2]


### Element

In [34]:
# Element related
Sz = Tor10.UniTensor(bonds=[Tor10.Bond(2),Tor10.Bond(2)],N_inbond=1,
                              dtype=torch.float64,
                              device=torch.device("cpu"))
Sz.SetElem([1, 0,
            0,-1])
print(Sz)

# Sparse
a = Tor10.UniTensor(bonds=[Tor10.Bond(3),Tor10.Bond(3)],N_inbond=1,is_diag=True)
print(a)

a.Todense()
print(a)

Tensor name: 
is_diag    : False
tensor([[ 1.,  0.],
        [ 0., -1.]], dtype=torch.float64)

Tensor name: 
is_diag    : True
tensor([0., 0., 0.], dtype=torch.float64)

Tensor name: 
is_diag    : False
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)



### Combine bonds

In [35]:
# CombineBonds:
bds_x = [Tor10.Bond(5),Tor10.Bond(5),Tor10.Bond(3)]
x = Tor10.UniTensor(bonds=bds_x, N_inbond=2, labels=[4,3,5])
y = Tor10.UniTensor(bonds=bds_x, N_inbond=2, labels=[4,3,5])
z = Tor10.UniTensor(bonds=bds_x, N_inbond=2, labels=[4,3,5])
x.Print_diagram()

x.CombineBonds([4,3])
x.Print_diagram()

y.CombineBonds([4,3])
y.Print_diagram()

z.CombineBonds([4,3],new_label=8)
z.Print_diagram()

tensor Name : 
tensor Rank : 3
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    4 __| 5         3 |__ 5  
        |             |     
    3 __| 5           |      
        |             |     
        ---------------     
lbl:4 Dim = 5 |
REGULAR :

lbl:3 Dim = 5 |
REGULAR :

lbl:5 Dim = 3 |
REGULAR :

tensor Name : 
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    3 __| 25        3 |__ 5  
        |             |     
        ---------------     
lbl:3 Dim = 25 |
REGULAR :

lbl:5 Dim = 3 |
REGULAR :

tensor Name : 
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    3 __| 25        3 |__ 5  
        |             |     
        ---------------     
lbl:3 Dim = 25 |
REGULAR :

lbl:5 Dim = 3 |
REGULAR :

tensor Name : 
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
       

### Contiguous

In [36]:
# Contiguous()
bds_x = [Tor10.Bond(5),Tor10.Bond(5),Tor10.Bond(3)]
x = Tor10.UniTensor(bonds=bds_x, N_inbond=1, labels=[4,3,5])
print(x.is_contiguous())
x.Permute(out_mapper=[2,1])
print(x.is_contiguous())
x.Contiguous()
print(x.is_contiguous())

True
False
True


### Permute

In [37]:
# Permute
bds_x = [Tor10.Bond(6),Tor10.Bond(5),Tor10.Bond(4),Tor10.Bond(3),Tor10.Bond(2)]
x = Tor10.UniTensor(bonds=bds_x, N_inbond=3,labels=[1,3,5,7,8])
y = Tor10.UniTensor(bonds=bds_x, N_inbond=3,labels=[1,3,5,7,8])
x.Print_diagram()

x.Permute(in_mapper=[0,2,1],out_mapper=[4,3])
x.Print_diagram()

y.Permute(in_mapper=[3,1,5],by_label=True)
y.Print_diagram()

tensor Name : 
tensor Rank : 5
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    1 __| 6         3 |__ 7  
        |             |     
    3 __| 5         2 |__ 8  
        |             |     
    5 __| 4           |      
        |             |     
        ---------------     
lbl:1 Dim = 6 |
REGULAR :

lbl:3 Dim = 5 |
REGULAR :

lbl:5 Dim = 4 |
REGULAR :

lbl:7 Dim = 3 |
REGULAR :

lbl:8 Dim = 2 |
REGULAR :

tensor Name : 
tensor Rank : 5
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    1 __| 6         2 |__ 8  
        |             |     
    5 __| 4         3 |__ 7  
        |             |     
    3 __| 5           |      
        |             |     
        ---------------     
lbl:1 Dim = 6 |
REGULAR :

lbl:5 Dim = 4 |
REGULAR :

lbl:3 Dim = 5 |
REGULAR :

lbl:8 Dim = 2 |
REGULAR :

lbl:7 Dim = 3 |
REGULAR :

tensor Name : 
tensor Rank : 5
on device   : cpu
is_diag     : F

### Reshape

In [38]:
# Reshape
bds_x = [Tor10.Bond(6),Tor10.Bond(5),Tor10.Bond(3)]
x = Tor10.UniTensor(bonds=bds_x, N_inbond=1,labels=[4,3,5])
x.Print_diagram()

y = x.Reshape([2,3,5,3],new_labels=[1,2,3,-1],N_inbond=2)
y.Print_diagram()
x.Print_diagram()

## GetTotalQnums
bd_sym_1 = Tor10.Bond(3,qnums=[[0, 2, 1, 0],
                                     [1, 1,-1, 1],
                                     [2,-1, 1, 0]])
bd_sym_2 = Tor10.Bond(4,qnums=[[-1, 0,-1, 3],
                                     [ 0, 0,-1, 2],
                                     [ 1, 0, 1, 0],
                                     [ 2,-2,-1, 1]])
bd_sym_3 = Tor10.Bond(2,qnums=[[-1,-2,-1,2],
                                      [ 1, 1, -2,3]])

sym_T = Tor10.UniTensor(bonds=[bd_sym_1,bd_sym_2,bd_sym_3],labels=[1,2,3],N_inbond=2,dtype=torch.float64)
tqin,tqout=sym_T.GetTotalQnums()
print(tqin)
print(tqout)

tensor Name : 
tensor Rank : 3
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    4 __| 6         5 |__ 3  
        |             |     
        |           3 |__ 5  
        |             |     
        ---------------     
lbl:4 Dim = 6 |
REGULAR :

lbl:3 Dim = 5 |
REGULAR :

lbl:5 Dim = 3 |
REGULAR :

tensor Name : 
tensor Rank : 4
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    1 __| 2         5 |__ 3  
        |             |     
    2 __| 3         3 |__ -1 
        |             |     
        ---------------     
lbl:1 Dim = 2 |
REGULAR :

lbl:2 Dim = 3 |
REGULAR :

lbl:3 Dim = 5 |
REGULAR :

lbl:-1 Dim = 3 |
REGULAR :

tensor Name : 
tensor Rank : 3
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    4 __| 6         5 |__ 3  
        |             |     
        |           3 |__ 5  
        |             |     
        ---------

### GetBlock

In [42]:
## GetBlock
bd_sym_1 = Tor10.Bond(3,qnums=[[0],[1],[2]])
bd_sym_2 = Tor10.Bond(4,qnums=[[-1],[2],[0],[2]])
bd_sym_3 = Tor10.Bond(5,qnums=[[4],[2],[-1],[5],[1]])
sym_T = Tor10.UniTensor(bonds=[bd_sym_1,bd_sym_2,bd_sym_3],N_inbond=2,labels=[10,11,12],dtype=torch.float64)
print("================================")
sym_T.Print_diagram()
print(sym_T)
q_in, q_out = sym_T.GetTotalQnums()
print('q_bra=', q_in)
print('q_ket=', q_out)

block_2 = sym_T.GetBlock(2)
print(block_2)

tensor Name : 
tensor Rank : 3
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
   10 __| 3         5 |__ 12 
        |             |     
   11 __| 4           |      
        |             |     
        ---------------     
lbl:10 Dim = 3 |
REGULAR : U1::  +0 +1 +2
         

lbl:11 Dim = 4 |
REGULAR : U1::  -1 +2 +0 +2
         

lbl:12 Dim = 5 |
REGULAR : U1::  +4 +2 -1 +5 +1
         

Tensor name: 
is_diag    : False
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float64)

q_bra= Dim = 12 |
REGULAR : U1::  -1 +2 +0 +2 +0 +3 +1 +3 +1 +4 +2 +4
         

q_ket= Dim = 5 |
REGULAR : U1::  +4 +2 -1 +5

In [44]:
print("======================")
sym_T_bf = Tor10.UniTensor(bonds=[bd_sym_1,bd_sym_2,bd_sym_3],N_inbond=2,labels=[10,11,12],is_blockform=True,dtype=torch.float64)
sym_T_bf.Print_diagram()
block_2bf = sym_T_bf.GetBlock(2) + 3
sym_T_bf.PutBlock(block_2bf,2)
print(sym_T_bf)

tensor Name : 
tensor Rank : 3
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
   10 __| 3         5 |__ 12 
        |             |     
   11 __| 4           |      
        |             |     
        ---------------     
lbl:10 Dim = 3 |
REGULAR : U1::  +2 +1 +0
         

lbl:11 Dim = 4 |
REGULAR : U1::  +2 +2 +0 -1
         

lbl:12 Dim = 5 |
REGULAR : U1::  +5 +4 +2 +1 -1
         

Tensor name: 
is_diag    : False
----------------
Block Qnum =  [-1]
tensor([[0.]], dtype=torch.float64)
----------------
Block Qnum =  [1]
tensor([[0.],
        [0.]], dtype=torch.float64)
----------------
Block Qnum =  [2]
tensor([[3.],
        [3.],
        [3.]], dtype=torch.float64)
----------------
Block Qnum =  [4]
tensor([[0.],
        [0.]], dtype=torch.float64)



In [45]:
sym_T_bf.to(torch.device("cpu"))

sym_T_bf += sym_T_bf
sym_T_bf += 4
print(sym_T_bf)
sym_T_bf -= sym_T_bf
sym_T_bf -= 7
print(sym_T_bf)
sym_T_bf *= sym_T_bf
sym_T_bf *= 7
print(sym_T_bf)
sym_T_bf /= sym_T_bf
sym_T_bf /= 7
print(sym_T_bf)

Tensor name: 
is_diag    : False
----------------
Block Qnum =  [-1]
tensor([[4.]], dtype=torch.float64)
----------------
Block Qnum =  [1]
tensor([[4.],
        [4.]], dtype=torch.float64)
----------------
Block Qnum =  [2]
tensor([[10.],
        [10.],
        [10.]], dtype=torch.float64)
----------------
Block Qnum =  [4]
tensor([[4.],
        [4.]], dtype=torch.float64)

Tensor name: 
is_diag    : False
----------------
Block Qnum =  [-1]
tensor([[-7.]], dtype=torch.float64)
----------------
Block Qnum =  [1]
tensor([[-7.],
        [-7.]], dtype=torch.float64)
----------------
Block Qnum =  [2]
tensor([[-7.],
        [-7.],
        [-7.]], dtype=torch.float64)
----------------
Block Qnum =  [4]
tensor([[-7.],
        [-7.]], dtype=torch.float64)

Tensor name: 
is_diag    : False
----------------
Block Qnum =  [-1]
tensor([[343.]], dtype=torch.float64)
----------------
Block Qnum =  [1]
tensor([[343.],
        [343.]], dtype=torch.float64)
----------------
Block Qnum =  [2]
tensor([

### Multiple quantum number

In [46]:
## multiple Qnum:
## U1 x U1 x U1 x U1
## U1 = {-2,-1,0,1,2}
## U1 = {-1,1}
## U1 = {0,1,2,3}
bd_sym_1 = Tor10.Bond(3,qnums=[[0, 2, 1, 0],
                               [1, 1,-1, 1],
                               [2,-1, 1, 0]])
bd_sym_2 = Tor10.Bond(4,qnums=[[-1, 0,-1, 3],
                               [ 0, 0,-1, 2],
                               [ 1, 0, 1, 0],
                               [ 2,-2,-1, 1]])
bd_sym_3 = Tor10.Bond(2,qnums=[[-1,-2,-1,2],
                               [ 1, 1, -2,3]])

sym_T = Tor10.UniTensor(bonds=[bd_sym_1,bd_sym_2,bd_sym_3],N_inbond=2,labels=[1,2,3],dtype=torch.float64)

tqin,tqout=sym_T.GetTotalQnums()
print(tqin)
print(tqout)
block_1123 = sym_T.GetBlock(1,1,-2,3)
print(block_1123)

Dim = 12 |
REGULAR : U1::  -1 +0 +1 +2 +0 +1 +2 +3 +1 +2 +3 +4
          U1::  +2 +2 +2 +0 +1 +1 +1 -1 -1 -1 -1 -3
          U1::  +0 +0 +2 +0 -2 -2 +0 -2 +0 +0 +2 +0
          U1::  +3 +2 +0 +1 +4 +3 +1 +2 +3 +2 +0 +1
         

Dim = 2 |
REGULAR : U1::  -1 +1
          U1::  -2 +1
          U1::  -1 -2
          U1::  +2 +3
         

Tensor name: 
is_diag    : False
tensor([[0.]], dtype=torch.float64)



### Contract

In [47]:
## Contract:
x = Tor10.UniTensor(bonds=[Tor10.Bond(5),Tor10.Bond(2),Tor10.Bond(4),Tor10.Bond(3)], N_inbond=2,labels=[6,1,7,8])
y = Tor10.UniTensor(bonds=[Tor10.Bond(4),Tor10.Bond(2),Tor10.Bond(3),Tor10.Bond(6)], N_inbond=2,labels=[7,2,10,9])
x.Print_diagram()
y.Print_diagram()
c = Tor10.Contract(x,y)
c.Print_diagram()
d = Tor10.Contract(y,x)
d.Print_diagram()

tensor Name : 
tensor Rank : 4
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    6 __| 5         4 |__ 7  
        |             |     
    1 __| 2         3 |__ 8  
        |             |     
        ---------------     
lbl:6 Dim = 5 |
REGULAR :

lbl:1 Dim = 2 |
REGULAR :

lbl:7 Dim = 4 |
REGULAR :

lbl:8 Dim = 3 |
REGULAR :

tensor Name : 
tensor Rank : 4
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    7 __| 4         3 |__ 10 
        |             |     
    2 __| 2         6 |__ 9  
        |             |     
        ---------------     
lbl:7 Dim = 4 |
REGULAR :

lbl:2 Dim = 2 |
REGULAR :

lbl:10 Dim = 3 |
REGULAR :

lbl:9 Dim = 6 |
REGULAR :

tensor Name : 
tensor Rank : 6
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    6 __| 5         3 |__ 8  
        |             |     
    1 __| 2         3 |__ 10 
        |          

In [48]:
## From_torch
x = torch.ones(3,3)
y = Tor10.From_torch(x,N_inbond=1,labels=[4,5])
y.Print_diagram()

x2 = torch.ones(3,4,requires_grad=True)
y2 = Tor10.From_torch(x2,N_inbond=1)
print(y2.requires_grad())

tensor Name : 
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    4 __| 3         3 |__ 5  
        |             |     
        ---------------     
lbl:4 Dim = 3 |
REGULAR :

lbl:5 Dim = 3 |
REGULAR :

True


### Network

In [50]:
# Network:
#==============================
ntwrk = Tor10.Network()
ntwrk.Fromfile("test.net")
A = Tor10.UniTensor([Tor10.Bond(3),Tor10.Bond(4),Tor10.Bond(3),Tor10.Bond(4)],N_inbond=2)
B = Tor10.UniTensor([Tor10.Bond(3),Tor10.Bond(2)],N_inbond=1)
C = Tor10.UniTensor([Tor10.Bond(4),Tor10.Bond(4)],N_inbond=1)
print(ntwrk)
ntwrk.Put("A",A)
print(ntwrk)
ntwrk.Put("B",B)
print(ntwrk)
ntwrk.Put("C",C)
print(ntwrk)
TOUT = ntwrk.Launch()
TOUT.Print_diagram()

==== Network ====
[x] A : -1 -2 ; 1 2 
[x] B : 1 ; 3 
[x] C : 2 ; 4 
TOUT : -1 -2 ; 3 4 

==== Network ====
[o] A : -1 -2 ; 1 2 
[x] B : 1 ; 3 
[x] C : 2 ; 4 
TOUT : -1 -2 ; 3 4 

==== Network ====
[o] A : -1 -2 ; 1 2 
[o] B : 1 ; 3 
[x] C : 2 ; 4 
TOUT : -1 -2 ; 3 4 

==== Network ====
[o] A : -1 -2 ; 1 2 
[o] B : 1 ; 3 
[o] C : 2 ; 4 
TOUT : -1 -2 ; 3 4 

tensor Name : 
tensor Rank : 4
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
   -1 __| 3         4 |__ 4  
        |             |     
   -2 __| 4         2 |__ 3  
        |             |     
        ---------------     
lbl:-1 Dim = 3 |
REGULAR :

lbl:-2 Dim = 4 |
REGULAR :

lbl:4 Dim = 4 |
REGULAR :

lbl:3 Dim = 2 |
REGULAR :



### Linear algebra

In [51]:
# linalg:
#============================
x = Tor10.From_torch(torch.arange(0.1,2.5,0.1).reshape(2,3,4).to(torch.float64),labels=[6,7,8],N_inbond=1)
x.Print_diagram()
factors, core = Tor10.Hosvd(x,order=[7,6,8],bonds_group=[2,1],by_label=True)
core.Print_diagram()
print(len(factors))
factors[0].Print_diagram()
factors[1].Print_diagram()

rep_x = core
for f in factors:
    rep_x = Tor10.Contract(rep_x,f)
#rep_x.Permute([6,7,8],N_inbond=1,by_label=True)
rep_x.Print_diagram()
print(rep_x - x)

a = Tor10.UniTensor(bonds=[Tor10.Bond(3),Tor10.Bond(4)],N_inbond=1)
b = Tor10.UniTensor(bonds=[Tor10.Bond(4),Tor10.Bond(5)],N_inbond=1)
c = Tor10.UniTensor(bonds=[Tor10.Bond(5),Tor10.Bond(6)],N_inbond=1)   
d = Tor10.UniTensor(bonds=[Tor10.Bond(6),Tor10.Bond(2)],N_inbond=1)

f = Tor10.Chain_matmul(a,b,c,d)
f.Print_diagram()




tensor Name : 
tensor Rank : 3
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    6 __| 2         3 |__ 7  
        |             |     
        |           4 |__ 8  
        |             |     
        ---------------     
lbl:6 Dim = 2 |
REGULAR :

lbl:7 Dim = 3 |
REGULAR :

lbl:8 Dim = 4 |
REGULAR :

tensor Name : 
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
   -1 __| 4           |      
        |             |     
   -2 __| 4           |      
        |             |     
        ---------------     
lbl:-1 Dim = 4 |
REGULAR :

lbl:-2 Dim = 4 |
REGULAR :

2
tensor Name : 
tensor Rank : 3
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    6 __| 2         3 |__ 7  
        |             |     
        |           4 |__ -1 
        |             |     
        ---------------     
lbl:6 Dim = 2 |
REGULAR :

lbl:7 Dim = 