# Tensor Network

In [1]:
import Tor10
import numpy as np 
import torch 
import copy

## Bond
Bond = local vector space.

In the following, we create a $d=2$ bond to represent $\{|+\rangle, |-\rangle\}$ or $\{\langle +|, \langle -|\}$.

In [2]:
bd = Tor10.Bond(2)
print(bd)

Dim = 2 |
REGULAR :



## Rank-1 tensor
* Ket: inbond.
* Bra: outbond.

In the basis of $\{|+\rangle, |-\rangle\}$, we create
$$
  |+\rangle \rightarrow 
  \left[
    \begin{array}{c}
    1 \\
    0
    \end{array}
  \right], \;
  |-\rangle \rightarrow 
  \left[
    \begin{array}{c}
    0 \\
    1
    \end{array}
  \right].
$$

In the basis of $\{\langle+|, \langle-|\}$, we create
$$
  \langle+| \rightarrow 
  \left[
    \begin{array}{cc}
    1 & 0
    \end{array}
  \right], \;
  \langle-| \rightarrow 
  \left[
    \begin{array}{cc}
    0 & 1
    \end{array}
  \right].
$$

### $|+\rangle$

In [3]:
# |+>
up_ket = Tor10.UniTensor(bonds=[bd], N_inbond=1, name="|+>")
up_ket.SetElem([1, 0])
print(up_ket) # issue: should display as column.
up_ket.Print_diagram()

Tensor name: |+>
is_diag    : False
tensor([1., 0.], dtype=torch.float64)

tensor Name : |+>
tensor Rank : 1
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2           |      
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :



### $|-\rangle$

In [4]:
dn_ket = Tor10.UniTensor(bonds=[bd], N_inbond=1, name="|->")
dn_ket.SetElem([0, 1])
print(dn_ket) # issue: should display as column.
dn_ket.Print_diagram()

Tensor name: |->
is_diag    : False
tensor([0., 1.], dtype=torch.float64)

tensor Name : |->
tensor Rank : 1
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2           |      
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :



### $\langle +|$

In [5]:
# <+|

# up_bra = up_ket.Reshape([2], N_inbond=0)
# up_bra.SetName('<+|')
# print(up_bra)
# up_bra.Print_diagram()

up_bra = Tor10.UniTensor(bonds=[bd], N_inbond=0, name="<+|")
up_bra.SetElem([1, 0])
print(up_bra) # issue: should display as column.
up_bra.Print_diagram()

Tensor name: <+|
is_diag    : False
tensor([1., 0.], dtype=torch.float64)

tensor Name : <+|
tensor Rank : 1
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
        |           2 |__ 0  
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :



In [6]:
# <+|
# up_bra = up_ket.Reshape([2], N_inbond=0)
# up_bra.SetName('<+|')
# print(up_bra)
# up_bra.Print_diagram()

In [7]:
# <-|

dn_bra = Tor10.UniTensor(bonds=[bd], N_inbond=0, name="<-|")
dn_bra.SetElem([0, 1])
print(dn_bra) # issue: should display as column.
dn_bra.Print_diagram()

# dn_bra = dn_ket.Reshape([2], N_inbond=0)
# up_bra.SetName('<-|')
# print(dn_bra)
# dn_bra.Print_diagram()

Tensor name: <-|
is_diag    : False
tensor([0., 1.], dtype=torch.float64)

tensor Name : <-|
tensor Rank : 1
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
        |           2 |__ 0  
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :



### Orthogonality $\langle i|j\rangle=\delta_{ij}$

In [8]:
for bra in [up_bra, dn_bra]:
    for ket in [up_ket, dn_ket]:
        braket = Tor10.Contract(bra, ket)
        print(braket.item())

1.0
0.0
0.0
1.0


### $|i\rangle\langle j|$

In [9]:
up_ket.SetLabels([0])
dn_bra.SetLabels([1])
print(up_ket.Print_diagram())
print(dn_bra.Print_diagram())

ketbra = Tor10.Contract(up_ket, dn_bra)
print(ketbra)
ketbra.Print_diagram()

tensor Name : |+>
tensor Rank : 1
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2           |      
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :

None
tensor Name : <-|
tensor Rank : 1
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
        |           2 |__ 1  
        |             |     
        ---------------     
lbl:1 Dim = 2 |
REGULAR :

None
Tensor name: 
is_diag    : False
tensor([[0., 1.],
        [0., 0.]], dtype=torch.float64)

tensor Name : 
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2         2 |__ 1  
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :

lbl:1 Dim = 2 |
REGULAR :



In [10]:
for ket in [up_ket, dn_ket]:
    for bra in [up_bra, dn_bra]:
        ket.SetLabels([0])
        bra.SetLabels([1])
        ketbra = Tor10.Contract(ket, bra)
        print(ketbra)

Tensor name: 
is_diag    : False
tensor([[1., 0.],
        [0., 0.]], dtype=torch.float64)

Tensor name: 
is_diag    : False
tensor([[0., 1.],
        [0., 0.]], dtype=torch.float64)

Tensor name: 
is_diag    : False
tensor([[0., 0.],
        [1., 0.]], dtype=torch.float64)

Tensor name: 
is_diag    : False
tensor([[0., 0.],
        [0., 1.]], dtype=torch.float64)



### Outter product: otimes $\otimes$

In [11]:
# Tor10.Otimes(up_ket, up_bra) # cannot do this

## Spin operators: $S^+, S^-, S^z$

In [12]:
Sp = Tor10.UniTensor(bonds=[bd,bd], N_inbond=1, name="Sp")
Sp.SetElem([0, 1,
            0, 0])
print(Sp)
print(Sp.Print_diagram())

Tensor name: Sp
is_diag    : False
tensor([[0., 1.],
        [0., 0.]], dtype=torch.float64)

tensor Name : Sp
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2         2 |__ 1  
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :

lbl:1 Dim = 2 |
REGULAR :

None


In [13]:
Sm = Tor10.UniTensor(bonds=[bd,bd], N_inbond=1, name="Sm")
Sm.SetElem([0, 0,
            1, 0])
print(Sm)
print(Sm.Print_diagram())

Tensor name: Sm
is_diag    : False
tensor([[0., 0.],
        [1., 0.]], dtype=torch.float64)

tensor Name : Sm
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2         2 |__ 1  
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :

lbl:1 Dim = 2 |
REGULAR :

None


In [14]:
Sz = Tor10.UniTensor(bonds=[bd,bd], N_inbond=1, name="Sz")
Sz.SetElem([+1, 0,
            0, -1])
print(Sz)
print(Sz.Print_diagram())

Tensor name: Sz
is_diag    : False
tensor([[ 1.,  0.],
        [ 0., -1.]], dtype=torch.float64)

tensor Name : Sz
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2         2 |__ 1  
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :

lbl:1 Dim = 2 |
REGULAR :

None


## Two-sites operator via outterproduct: otimes $\otimes$

In [15]:
SpSm = Tor10.linalg.Otimes(Sp, Sm)
SmSp = Tor10.linalg.Otimes(Sm, Sp)
SzSz = Tor10.linalg.Otimes(Sz, Sz)
print(SpSm)
print(SmSp)
print(SzSz)

Tensor name: 
is_diag    : False
tensor([[0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

Tensor name: 
is_diag    : False
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)

Tensor name: 
is_diag    : False
tensor([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  0., -0.],
        [ 0.,  0., -1., -0.],
        [ 0., -0., -0.,  1.]], dtype=torch.float64)



In [16]:
print(SpSm+SmSp)

Tensor name: 
is_diag    : False
tensor([[0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)



## Two-sites wavefunction

In [17]:
up1_ket = copy.deepcopy(up_ket)
up1_ket.SetName('|+1>')
up2_ket = copy.deepcopy(up_ket)
up2_ket.SetName('|+2>')


up1_ket.SetLabels([0])
up2_ket.SetLabels([1])
print(up1_ket.Print_diagram())
print(up2_ket.Print_diagram())

up1up2_ket = Tor10.Contract(up1_ket, up2_ket)
up1up2_ket.SetName('|++>')
print(up1up2_ket) # issue: should be a single column?
up1up2_ket.Print_diagram()

tensor Name : |+1>
tensor Rank : 1
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2           |      
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :

None
tensor Name : |+2>
tensor Rank : 1
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    1 __| 2           |      
        |             |     
        ---------------     
lbl:1 Dim = 2 |
REGULAR :

None
Tensor name: |++>
is_diag    : False
tensor([[1., 0.],
        [0., 0.]], dtype=torch.float64)

tensor Name : |++>
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2           |      
        |             |     
    1 __| 2           |      
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :

lbl:1 Dim = 2 |
REGULAR :



In [18]:
dn1_ket = copy.deepcopy(dn_ket)
dn2_ket = copy.deepcopy(dn_ket)

dn1_ket.SetLabels([0])
dn2_ket.SetLabels([1])
# print(up1_ket.Print_diagram())
# print(up2_ket.Print_diagram())

dn1dn2_ket = Tor10.Contract(dn1_ket, dn2_ket)
print(dn1dn2_ket) # issue: should be a single column?
dn1dn2_ket.Print_diagram()

Tensor name: 
is_diag    : False
tensor([[0., 0.],
        [0., 1.]], dtype=torch.float64)

tensor Name : 
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    0 __| 2           |      
        |             |     
    1 __| 2           |      
        |             |     
        ---------------     
lbl:0 Dim = 2 |
REGULAR :

lbl:1 Dim = 2 |
REGULAR :



### Bell state

In [19]:
Bell1 = up1up2_ket + dn1dn2_ket
print(Bell1)

Tensor name: 
is_diag    : False
tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)



In [20]:
u, s, v = Tor10.linalg.Svd(Bell1)
s

Tensor name: 
is_diag    : True
tensor([1., 1.], dtype=torch.float64)


In [21]:
y = Tor10.UniTensor(bonds=[Tor10.Bond(3),Tor10.Bond(4)], N_inbond=1)
y.SetElem([1,1,0,1, 
           0,0,0,1,
           1,1,0,0])
print(y)

Tensor name: 
is_diag    : False
tensor([[1., 1., 0., 1.],
        [0., 0., 0., 1.],
        [1., 1., 0., 0.]], dtype=torch.float64)



In [22]:
u,s,v = Tor10.linalg.Svd(y)

In [23]:
x = Tor10.From_torch(torch.arange(0.1,2.5,0.1).reshape(2,3,4).to(torch.float64),labels=[6,7,8],N_inbond=1)
>>> x.Print_diagram()

tensor Name : 
tensor Rank : 3
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
    6 __| 2         3 |__ 7  
        |             |     
        |           4 |__ 8  
        |             |     
        ---------------     
lbl:6 Dim = 2 |
REGULAR :

lbl:7 Dim = 3 |
REGULAR :

lbl:8 Dim = 4 |
REGULAR :



In [24]:
factors, core = Tor10.Hosvd(x,order=[7,6,8],bonds_group=[2,1],by_label=True)

In [25]:
core.Print_diagram()
print(core)

tensor Name : 
tensor Rank : 2
on device   : cpu
is_diag     : False
        ---------------     
        |             |     
   -1 __| 4           |      
        |             |     
   -2 __| 4           |      
        |             |     
        ---------------     
lbl:-1 Dim = 4 |
REGULAR :

lbl:-2 Dim = 4 |
REGULAR :

Tensor name: 
is_diag    : False
tensor([[ 6.9951e+00,  4.4409e-16, -4.4409e-16,  4.4409e-16],
        [ 8.7430e-16, -2.6205e-01,  1.2490e-16, -2.2204e-16],
        [ 2.0649e-16, -1.5878e-16, -1.0240e-07,  9.4612e-17],
        [ 7.1613e-16,  2.2483e-17,  2.3548e-17, -2.8853e-08]],
       dtype=torch.float64)

